/**
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight any
 * @framerIntrinsicWidth 150
 * @framerIntrinsicHeight 150
 */import{jsx as _jsx,jsxs as _jsxs,Fragment as _Fragment}from"react/jsx-runtime";import{useState,useRef,useMemo}from"react";import{motion,AnimatePresence}from"framer-motion";/**
 * PAINT REVEAL COMPONENT
 * Interactive paint-to-reveal effect with custom brush strokes that fade away.
 * Mobile: Double-tap to toggle paint mode, allows scrolling when inactive.
 */export default function Paint_Reveal(props){const{baseImage,revealImage,brushTexture,brushSize,fadeDuration,maxStamps,showIndicator,indicatorText,indicatorColor,borderRadius}=props;const[stamps,setStamps]=useState([]);const[isPaintMode,setIsPaintMode]=useState(false);const containerRef=useRef(null);const idCounter=useRef(0);const lastTapRef=useRef(0);const maskId=useMemo(()=>"paint-mask-"+Math.random().toString(36).substr(2,9),[]);// Calculate responsive brush size based on container width
const getResponsiveBrushSize=()=>{if(!containerRef.current)return brushSize;const containerWidth=containerRef.current.offsetWidth;// Scale brush size proportionally on smaller screens
if(containerWidth<768){return brushSize*.6// 60% size on mobile
;}else if(containerWidth<1024){return brushSize*.8// 80% size on tablet
;}return brushSize;};// Handle double-tap detection for mobile
const handleDoubleTap=e=>{const now=Date.now();const timeSince=now-lastTapRef.current;if(timeSince<300&&timeSince>0){// Double tap detected - toggle paint mode
setIsPaintMode(prev=>!prev);e.preventDefault();}lastTapRef.current=now;};// Add paint stamp at pointer/touch location
const addStamp=e=>{if(!containerRef.current)return;// On mobile, only paint if paint mode is active
if(e.type.includes("touch")&&!isPaintMode){return;}// Prevent scrolling when in paint mode
if(e.type.includes("touch")&&isPaintMode){e.preventDefault();}const rect=containerRef.current.getBoundingClientRect();const responsiveBrushSize=getResponsiveBrushSize();// Handle both touch and mouse events
let clientX,clientY;if(e.touches&&e.touches.length>0){clientX=e.touches[0].clientX;clientY=e.touches[0].clientY;}else{clientX=e.clientX;clientY=e.clientY;}const x=clientX-rect.left-responsiveBrushSize/2;const y=clientY-rect.top-responsiveBrushSize/2;const newStamp={id:idCounter.current++,x,y,size:responsiveBrushSize};setStamps(prev=>{const next=[...prev,newStamp];return next.length>maxStamps?next.slice(next.length-maxStamps):next;});};// Remove stamp after fade animation completes
const removeStamp=id=>{setStamps(prev=>prev.filter(s=>s.id!==id));};return /*#__PURE__*/_jsx("div",{ref:containerRef,onPointerMove:e=>e.buttons>0&&addStamp(e),onPointerDown:e=>!e.pointerType.includes("touch")&&addStamp(e),onTouchStart:e=>{handleDoubleTap(e);if(isPaintMode)addStamp(e);},onTouchMove:e=>isPaintMode&&addStamp(e),style:{width:"100%",height:"100%",minWidth:150,minHeight:150,position:"relative",overflow:"hidden",touchAction:isPaintMode?"none":"auto",WebkitUserSelect:"none",userSelect:"none",cursor:"crosshair",borderRadius:borderRadius},children:!baseImage&&!revealImage?/*#__PURE__*/_jsx("div",{style:{width:"100%",height:"100%",minWidth:150,minHeight:150,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",background:"#F3EEFF",gap:"8px",padding:"40px",position:"absolute",inset:0},children:/*#__PURE__*/_jsxs("div",{style:{textAlign:"center",color:"#9966FF",maxWidth:"180px"},children:[/*#__PURE__*/_jsx("h3",{style:{fontSize:"14px",fontWeight:"500",margin:"0 0 4px 0",fontFamily:"Inter, system-ui, sans-serif"},children:"Paint Reveal"}),/*#__PURE__*/_jsx("p",{style:{fontSize:"12px",fontWeight:"400",margin:0,fontFamily:"Inter, system-ui, sans-serif",color:"#B38FFF"},children:"Add images to see paint reveal effect"})]})}):/*#__PURE__*/_jsxs(_Fragment,{children:[isPaintMode&&showIndicator&&/*#__PURE__*/_jsx(motion.div,{initial:{opacity:0,y:-10},animate:{opacity:1,y:0},exit:{opacity:0,y:-10},style:{position:"absolute",top:"16px",left:"50%",transform:"translateX(-50%)",background:indicatorColor,color:"#fff",padding:"6px 12px",borderRadius:"6px",fontSize:"12px",fontWeight:"500",zIndex:10,pointerEvents:"none",backdropFilter:"blur(8px)",boxShadow:"0 2px 8px rgba(0,0,0,0.15)"},children:indicatorText}),/*#__PURE__*/_jsx("div",{style:{position:"absolute",inset:0,backgroundImage:`url(${baseImage})`,backgroundSize:"cover",backgroundPosition:"center"}}),/*#__PURE__*/_jsx("div",{style:{position:"absolute",inset:0,backgroundImage:`url(${revealImage})`,backgroundSize:"cover",backgroundPosition:"center",WebkitMask:`url(#${maskId})`,mask:`url(#${maskId})`}}),/*#__PURE__*/_jsx("svg",{style:{position:"absolute",width:0,height:0},children:/*#__PURE__*/_jsx("defs",{children:/*#__PURE__*/_jsxs("mask",{id:maskId,children:[/*#__PURE__*/_jsx("rect",{width:"100%",height:"100%",fill:"black"}),/*#__PURE__*/_jsx(AnimatePresence,{children:stamps.map(s=>/*#__PURE__*/_jsx(motion.image,{href:brushTexture,x:s.x,y:s.y,width:s.size,height:s.size,initial:{opacity:0},animate:{opacity:1},exit:{opacity:0},transition:{duration:fadeDuration,ease:"linear"},onAnimationComplete:()=>removeStamp(s.id)},s.id))})]})})})]})});}
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"Paint_Reveal","slots":[],"annotations":{"framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Paint_Reveal.map